version: '3.7'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    hostname: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: node-user
      MYSQL_PASSWORD: 123456

    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      test:
        aliases:
          - mysql

networks:
  service_net:
  test:
    external: false

volumes:
  dbdata: